name: $(Major).$(Minor).$(Patch).$(Revision)

trigger:
- ci

variables:
- group: Version
- name: Revision
  value: $[counter(format('{0}.{1}.{2}', variables.Major, variables.Minor, variables.Patch), 1)]
- name: AssemblyVersion
  value: $(Major).$(Minor).$(Patch)
- name: PackageVersion
  value: $(Major).$(Minor).$(Patch).$(Revision)

jobs:
- template: template.yml
  parameters:
    strategy:
      matrix:
        Debug:
          BuildConfiguration: Debug
        Release:
          BuildConfiguration: Release
    artifacts:
    - displayName: Publish .NET 2.0
      inputs:
        Path: artifacts\WinSW.NET2.exe
        Name: WinSW.NET2.exe_$(BuildConfiguration)
    - displayName: Publish .NET 4.0
      inputs:
        Path: artifacts\WinSW.NET4.exe
        Name: WinSW.NET4.exe_$(BuildConfiguration)
    - displayName: Publish .NET 4.6.1
      inputs:
        Path: artifacts\WinSW.NET461.exe
        Name: WinSW.NET461.exe_$(BuildConfiguration)
    - displayName: Publish .NET Core 3.1
      inputs:
        Path: artifacts\WinSW.NETCore31.zip
        Name: WinSW.NETCore31.zip_$(BuildConfiguration)
    - displayName: Publish .NET Core 3.1 x64
      inputs:
        Path: artifacts\WinSW.NETCore31.x64.exe
        Name: WinSW.NETCore31.x64.exe_$(BuildConfiguration)
    - displayName: Publish .NET Core 3.1 x86
      inputs:
        Path: artifacts\WinSW.NETCore31.x86.exe
        Name: WinSW.NETCore31.x86.exe_$(BuildConfiguration)
    - displayName: Publish Nuget
      inputs:
        Path: $(Build.ArtifactStagingDirectory)\WinSW.$(PackageVersion).nupkg
        Name: WinSW.nupkg_$(BuildConfiguration)
